# Generated by Django 2.2 on 2020-10-24 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_and_reg_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='password',
            new_name='password_hash',
        ),
    ]
